require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - '*.cmlz'
  TargetRubyVersion: 3.1
  SuggestExtensions: false


Style/Documentation:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledocumentation

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false